Add xml-doc comments to RepositoryReadConductor. Fixes issue #11
AndcultureCode/AndcultureCode.CSharp.Conductors pull request #15
Opened 2020-09-25 13:27 UTC by vmrocha

Adds xml-doc comments to the RepositoryReadConductor class public members.

- [ ] Related GitHub issue(s) linked in PR description
- [ ] Destination branch merged, built and tested with your changes
- [ ] Code formatted and follows best practices and patterns
- [ ] Code builds cleanly (no _additional_ warnings or errors)
- [ ] Manually tested
- [ ] Automated tests are passing
- [ ] No _decreases_ in automated test coverage
- [ ] Documentation updated (readme, docs, comments, etc.)
- [ ] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

2020-09-25 20:42 UTC, brandongregoryscott requested changes
Thanks for the contribution, @vmrocha! Left some feedback for some revisions to the descriptions. Also, please be mindful of the pull request checklist and fill out any steps that apply to the given issue. This is just a documentation update, so most of them probably _won't_ apply, but please at least link the related issue in the description with [closing keywords](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#closing-an-issue-in-the-same-repository)

2020-09-25 20:42 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Conductors/RepositoryReadConductor.cs
> +        /// Creates and instance of RepositoryReadConductor for an <see cref="IRepository{T}"/> instance.
Typo - `and` vs `an`

2020-09-25 20:42 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Conductors/RepositoryReadConductor.cs
> +        /// <param name="ignoreQueryFilters">If previous applied filters should be ignore.</param>
Thanks for filling these in! While this is close, this parameter actually applies to the concept of [EF Core Global Query Filters](https://docs.microsoft.com/en-us/ef/core/querying/filters). This comment would better read something along the lines of "If true, global query filters will be ignored for this query." The same would apply for any other methods in this conductor that have the same param.

2020-09-26 00:58 UTC, vmrocha commented on src/AndcultureCode.CSharp.Conductors/RepositoryReadConductor.cs
> +        /// Creates and instance of RepositoryReadConductor for an <see cref="IRepository{T}"/> instance.
Good catch!

2020-09-26 00:59 UTC, vmrocha commented on src/AndcultureCode.CSharp.Conductors/RepositoryReadConductor.cs
> +        /// <param name="ignoreQueryFilters">If previous applied filters should be ignore.</param>
Thank you for explaining that. I didn't know!

2020-09-26 01:23 UTC, brandongregoryscott approved these changes
Thanks for making those updates, @vmrocha!

2020-09-26 01:25 UTC, merged