Added XML comments for the repositoryUpdateConductor methods
AndcultureCode/AndcultureCode.CSharp.Conductors pull request #16
Opened 2020-09-28 18:20 UTC by SaidShah

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

#12

2020-09-29 10:23 UTC, wintondeshong requested changes
@SaidShah aside from the minor removal of the newline, good to go. Let us know when you've made the change and we will merge.

2020-09-29 10:23 UTC, wintondeshong commented on src/AndcultureCode.CSharp.Conductors/RepositoryUpdateConductor.cs
Nitpick: Mind removing this extra newline?

2020-09-29 12:52 UTC, SaidShah commented
@wintondeshong thanks, it should be good to go now.

2020-09-29 13:21 UTC, wintondeshong approved these changes
looks good! Thanks @saidshahdev

2020-09-29 13:22 UTC, merged

2021-04-14 20:21 UTC, brandongregoryscott commented
@all-contributors add @SaidShah for doc