Add xml comments for repository conductor
AndcultureCode/AndcultureCode.CSharp.Conductors pull request #20
Opened 2020-10-02 12:51 UTC by SaidShah

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Closes #8

2020-10-02 17:15 UTC, brandongregoryscott requested changes
Just a minor typo to be fixed up @SaidShah

2020-10-02 17:15 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Conductors/RepositoryConductor.cs
> +        #endregion Properties0
Typo

2020-10-05 13:36 UTC, SaidShah commented on src/AndcultureCode.CSharp.Conductors/RepositoryConductor.cs
> +        #endregion Properties0
@brandongregoryscott Thanks for catching that, it has been fixed.

2020-10-05 18:15 UTC, brandongregoryscott approved these changes

2020-10-05 18:15 UTC, merged