Added the coverlet nuget package and updated readme
AndcultureCode/AndcultureCode.CSharp.Conductors pull request #27
Opened 2020-11-06 13:50 UTC by SaidShah

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Closes #23

2020-11-06 23:56 UTC, brandongregoryscott requested changes
Hey @SaidShah, sorry I didn't get to this earlier. Looks like there's a conflict now - can you clear that up and I'll approve & merge? Thanks!

2020-11-09 13:17 UTC, SaidShah commented
@brandongregoryscott - The conflict should be resolved now. 👍

2020-11-09 13:27 UTC, brandongregoryscott requested changes

2020-11-09 13:27 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Conductors.Tests/AndcultureCode.CSharp.Conductors.Tests.csproj
> +    <PackageReference Include="AndcultureCode.CSharp.Core" Version="0.7.0"/>
@SaidShah I believe this will downgrade the core dependency - can you swap this back to 0.8.0?

2020-11-09 13:33 UTC, SaidShah commented on test/AndcultureCode.CSharp.Conductors.Tests/AndcultureCode.CSharp.Conductors.Tests.csproj
> +    <PackageReference Include="AndcultureCode.CSharp.Core" Version="0.7.0"/>
😳 I just saw that, I swaped it to be 0.8.0 thanks.

2020-11-09 13:43 UTC, brandongregoryscott approved these changes

2020-11-09 13:43 UTC, merged